### ISSUE TITLE
Redundant assets in unity package

### ISSUE THREAD

**Issue by Nesit1** [kirevdokimov/Unity-UI-Rounded-Corners#12]
Hello @kirevdokimov !

First of all - that's one really great asset, it makes working with UI much easier.

There is one minor issue with package.json - it includes gifs and examples, that aren't really required in final version downloaded via Unity Package manager.

Consider adding following lines into package.json: 
`    "files": [
        "/LICENSE",
        "/LICENSE.meta",
        "/README.md",
        "/README.md.meta",
        "/package.json",
        "/package.json.meta",
        "/UiRoundedCorners",
        "/UiRoundedCorners.meta"
    ]`

It should filter out heavy gifs and examples, thanks!

**Comment by kirevdokimov** [comment]
Thank you @Nesit1!
