### ISSUE TITLE
Buggy inside ScrollRect

### ISSUE THREAD

**Issue by hippogamesunity** [kirevdokimov/Unity-UI-Rounded-Corners#15]
Hello! If you put an image inside ScrollRect and try changing rounding radius, nothing happens. It only works outside of ScrollRect.
Seems it conflicts with Mask component.

**Comment by hippogamesunity** [comment]
Was able to workaround these issues by introducing new materials automatically
![image](https://user-images.githubusercontent.com/7318172/105053972-90694b00-5a82-11eb-81da-14483113b0cc.png)

**Comment by kirevdokimov** [comment]
The issue is solved with version 3
