### ISSUE TITLE
Need to refresh ImageWithCorners script after downloading image.

### ISSUE THREAD

**Issue by karolsenami** [kirevdokimov/Unity-UI-Rounded-Corners#17]
After resetting the image after downloading it from an URL, I have to call Refresh method form the RoundedCorners script otherwise the corners are buggy and not rounded.

To do this I set the Refresh method as public instead of private.

Not sure this is an issue but I posted this if someone else has this issue.

**Comment by kirevdokimov** [comment]
Refresh method is public since version 3.0.0
