### ISSUE TITLE
Version 3 won't build

### ISSUE THREAD

**Issue by russellquinn** [kirevdokimov/Unity-UI-Rounded-Corners#21]
Unity `2020.3.26f1`
UI-rounded-corners `3.0.0`

If I try and build the project, I get a slew of editor-namespace errors:
`The type or namespace name 'CustomEditor' could not be found (are you missing a using directive or an assembly reference?)`

From googling around, it seem like Unity is not consistent when handling Editor folders in packages during a build, so we need to wrap all editor scripts in:

```
#if UNITY_EDITOR 

#endif
```

**Comment by russellquinn** [comment]
I made a pull request with the fix.

**Comment by antonsmetanin** [comment]
My bad. I forgot to add the asmdef file and, what's more important, forgot to test the build.
