### ISSUE TITLE
RawImage support

### ISSUE THREAD

**Issue by diegomazala** [kirevdokimov/Unity-UI-Rounded-Corners#30]
I tried to upload an improvement but don't have permissions.
I would suggest you to change the Image dependency to MaskableGraphic. Then, we would be able to use RawImage also.

ImageWithIndependentRoundedCorners.cs and ImageRoundedCorners.cs
`[HideInInspector, SerializeField] private MaskableGraphic image;`

ImageWithIndependentRoundedCornersInspector.cs and ImageWithRoundedCornersInspector.cs
`if (!script.TryGetComponent<MaskableGraphic>(out var _)) {
                EditorGUILayout.HelpBox("This script requires an MaskableGraphic (Image or RawImage) component on the same gameobject", MessageType.Warning);
            }`

**Comment by univeous** [comment]
Your suggestions look good. I made a pull request #32 based on this 🙂

**Comment by diegomazala** [comment]
Your work looks great
I'm glad for making a simple contribution
