### ISSUE TITLE
Support SpriteAtals

### ISSUE THREAD

**Issue by malibu-dev-nsuslab** [kirevdokimov/Unity-UI-Rounded-Corners#40]
Thanks for making a great plugin.

Unfortunately, this shader does not work with spriteAtlas.

In editor mode, spriteAtlas is treated as 1 texture, so it seems to work normally,

After building, the uv coordinates are changed to the uv coordinates in the packed texture, so it cannot be used.

Could you please fix it to support spriteatlas?

**Comment by kirevdokimov** [comment]
Support for the feature was added thanks to @xiabob!
