### ISSUE TITLE
Difference Radius Between IOS And Android

### ISSUE THREAD

**Issue by thai18122000** [kirevdokimov/Unity-UI-Rounded-Corners#47]
I use ImageWithRoundedCorners in my project and there are some differences or the corner if I switch to other platforms. For example, If I set the radius for the Android platform as 150, the image looks great. But if I switch to IOS, I have to increase to 300 to look good as Android. It is just like you have to double the value in the IOS platform. Thank you for the great package.

**Comment by thai18122000** [comment]
Well, I find out a hotfix for this, not optimize but at least it'll fix this problem.
You can use Scripting to define symbol in unity and edit the ImageWithRoundedCorners script.

`        public void Refresh()
        {
            var rect = ((RectTransform)transform).rect;

            //Multiply radius value by 2 to make the radius value appear consistent with ImageWithIndependentRoundedCorners script.
            //Right now, the ImageWithIndependentRoundedCorners appears to have double the radius than this.
#if UNITY_IOS
		    material.SetVector(Props, new Vector4(rect.width, rect.height, radius * 2, 0));   
#else
            material.SetVector(Props, new Vector4(rect.width, rect.height, radius, 0));
#endif
        }`

**Comment by kirevdokimov** [comment]
Oh wow, looks like some weird platform-specific kind of thing
