### ISSUE TITLE
Errors on last version

### ISSUE THREAD

**Issue by lucanasistemi** [kirevdokimov/Unity-UI-Rounded-Corners#58]
Library\PackageCache\com.nobi.roundedcorners@5600be023e\UiRoundedCorners\Editor\ImageWithRoundedCornersInspector.cs(5,53): error CS0246: The type or namespace name 'CanEditMultipleObjectsCanEditMultipleObjectsAttribute' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.nobi.roundedcorners@5600be023e\UiRoundedCorners\Editor\ImageWithRoundedCornersInspector.cs(5,53): error CS0246: The type or namespace name 'CanEditMultipleObjectsCanEditMultipleObjects' could not be found (are you missing a using directive or an assembly reference?)

**Comment by OmarAlFarajat** [comment]
It's a typo `CanEditMultipleObjectsCanEditMultipleObjects` → `CanEditMultipleObjects`

**Comment by kirevdokimov** [comment]
The issue fixed in #59
